// This file is generated by Astro DB
declare module 'astro:db' {
	export const Comment: import("@astrojs/db/runtime").Table<
		"Comment",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Comment","primaryKey":true}},"postSlug":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"postSlug","collection":"Comment","primaryKey":false,"optional":false}},"postType":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"postType","collection":"Comment","default":"post","primaryKey":false,"optional":false}},"author":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"author","collection":"Comment","primaryKey":false,"optional":false}},"body":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"body","collection":"Comment","primaryKey":false,"optional":false}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"Comment"}}}
	>;
	export const Rating: import("@astrojs/db/runtime").Table<
		"Rating",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Rating","primaryKey":true}},"postSlug":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"postSlug","collection":"Rating","primaryKey":false,"optional":false}},"postType":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"postType","collection":"Rating","default":"post","primaryKey":false,"optional":false}},"value":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"value","collection":"Rating","primaryKey":false,"optional":false}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"Rating"}}}
	>;
}
